[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.7.6"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@uniswap/v3-core/=lib/v3-core/',
    '@uniswap/v3-periphery/=lib/v3-periphery/',
    '@uniswap/lib/=lib/uniswap-lib/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    'base64-sol/=lib/base64/',
    'openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/',
    'v3-core/=lib/v3-core/',
    'v3-periphery/=lib/v3-periphery/contracts/'
]