[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# remappings = [
# 	"@uniswap/v3-core/=lib/v3-core/",
# 	"@uniswap/v3-periphery/=lib/v3-periphery/",
# 	"@openzeppelin/=lib/openzeppelin-contracts/"
# ]
remappings = [
    'forge-std/=lib/forge-std/src/',
    '@uniswap/v3-core/=lib/v3-core/',
    '@uniswap/v3-periphery/=lib/v3-periphery/',
    '@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/',
    '@uniswap/v4-core/=lib/v4-template/lib/uniswap-hooks/lib/v4-core/',
    '@uniswap/v4-periphery/=lib/v4-template/lib/uniswap-hooks/lib/v4-periphery/',
    'v4-core/=lib/v4-template/lib/uniswap-hooks/lib/v4-core/',
    'v4-periphery/=lib/v4-template/lib/uniswap-hooks/lib/v4-periphery/',
    'hookmate/=lib/v4-template/lib/hookmate/src/',
    'permit2/=lib/v4-template/lib/uniswap-hooks/lib/v4-periphery/lib/permit2/',
    'solmate/=lib/v4-template/lib/uniswap-hooks/lib/v4-core/lib/solmate/'
]
optimizer = true		
optimizer_runs = 10000
via-ir = true


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
